---
    
#    - name: Gather EC2 Metadata Facts
#      ec2_metadata_facts:
#
#    - name: install yum dependancies
#      yum:
#        name: unzip

    - name: remove previous AWS CLI version
      shell: |
        sudo rm /usr/local/bin/aws
        sudo rm /usr/local/bin/aws_completer
        sudo rm -rf /usr/local/aws-cli

    - name: Installing AWS CLI
      shell: |
        cd ~
        sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        sudo unzip awscliv2.zip
        sudo ./aws/install --bin-dir /bin --install-dir /usr/local/aws-cli

    - name: Removing Junk Files
      shell: |
        cd ~
        rm -rf aws
        rm -rf awscliv2.zip

    # Add AWS credential profile for root (become) user
    - name: Creates .aws directory
      file:
        dest: /root/.aws/
        state: directory
